### ISSUE TITLE
how to use customize button in datatable ,

### ISSUE THREAD

**Issue by soujanna-coder** [AndreSouzaAbreu/vue-data-table#14]
i want to use customize button in my datattable

**Comment by AndreSouzaAbreu** [comment]
Hello, which button do you want to customize? And how do you want to customize? If you only want to change the styles, you can override it with CSS

**Comment by soujanna-coder** [comment]
how to use action button like view , edit ,delete ,
can you send me an example how to use action button and action component

**Comment by soujanna-coder** [comment]
actionMode: "multiple", 
how to use this one

**Comment by AndreSouzaAbreu** [comment]
>how to use action button like view , edit ,delete ,
>can you send me an example how to use action button and action component

This was only available in previous versions of Vue Data Table. I think it was available on version 1 and probably version 2 too. It is not available on version 3 because of the following: Since version 3 (and latest releases of version 2) it is possible to pass a custom Vue component to render a column. Therefore, I decided to remove action buttons because you can provide a Vue Component to render your buttons anyway you like.

Here is an example of how you can use action buttons:

```html
<template>
  <button class="btn btn-danger" @click="triggerSomeAction()">
    <i class="fa fa-trash"></i> <!-- trash icon -->
  </button>
</template>
<script>
export default {
  name: "ButtonDelete",
  methods: {
    triggerSomeAction() {
      console.log("I'm about to delete user:", this.data.username);
      console.log("The user's gender is:", this.data.gender); 
    }
  },
  props: {
    // prop below is REQUIRED:
    data: {
      type: Object
    }
  }
}
</script>
```

Then, you need to pass this component to VueDataTable;

```html
<template>
  <data-table v-bind="dataTableProps">
</template>
<script>
import ButtonDelete from "./ButtonDelete.vue"
import { users } from "./users.js"
export default {
  name: "DashboardExample",
  data() {
    return {
      dataTableProps: {
        data: users,
        columns: [
          {
            title: "User name",
            key: "username"
          },
          {
            key: "gender"
            // since title is not specified, it will be "Gender"
          },
          // LINES BELOW IS WHAT YOU WANT
          {
            title: "ACTIONS",
            component: ButtonDelete
          }
        ]
      }
    }
  }
}
</script>
```

>actionMode: "multiple",
>how to use this one

If you want to use older versions of `vue-data-table`, then  you just need to pass the following props to VueDataTable:

```javascript
{
  data: [/* an array of objects*/],
  columns: [/* another array of objects */],
  actionMode: "multiple",
  actions: ["edit", "view", "delete"] // these three actions are available by default
  // if you want to add other action buttons you need to read the old docs
}
```

Let me know if you got it

**Comment by tannguyencse19** [comment]
In your code demo, it still appear which make me confused when searching in the code 
![image](https://user-images.githubusercontent.com/62830718/133333540-0a488bc7-c1d7-45cc-b954-453a2d509d64.png)
