### ISSUE TITLE
Component is not replacing original value

### ISSUE THREAD

**Issue by joey-carlisle4** [AndreSouzaAbreu/vue-data-table#27]
When I use the component column option and pass in a component, both the new component and original span show up in the table.  This is adding duplicate values.  
![image](https://user-images.githubusercontent.com/53163998/131702905-d5391e1d-44ca-4c51-ba5f-dde87ce2e008.png)

EDIT:: When I remove the "key" from the column object, it removes the extra value.  This is contradictory to the example in the readme.  It also removes the searching from that column

**Comment by joey-carlisle4** [comment]
![image](https://user-images.githubusercontent.com/53163998/131710164-a489af90-8b79-42fe-9701-91e7b3b907ca.png)

The component and span should be mutually exclusive

**Comment by joey-carlisle4** [comment]
you could probably just do a v-else and it would work

**Comment by AndreSouzaAbreu** [comment]
Yes, that is true! The problem is that I've been unable to build the
VueDataTable after fixing this bug. I tried to run `npm run build` but got some
weird issues with `node-sass`, and `sass-loader`, which are dev dependecies.

Npm packages are really a mess: a single library depends on several libraries,
which depends on other several libraries, and one broken dependecy breaks it all.
This happens often and shouldn't happen: if `npm install` works for a given `package.json`
at a point in the time, it should work any time in the future too.

For while, here is a quick workaround for you: delete the `key` property of the object you are
passing. I mean, only pass the `title` and the `component` property. It should work

**Comment by joey-carlisle4** [comment]
are you building locally and then pushing to the repo?

**Comment by AndreSouzaAbreu** [comment]
I'm building locally. I finally was able to fix the issue :)
I will let this link here just in case I get in trouble again:

https://github.com/vuejs/vue-cli/issues/5986

Anyway, I need to make some tests first and later I will release a new minor version.

**Comment by joey-carlisle4** [comment]
awesome thanks

**Comment by joey-carlisle4** [comment]
Seems to work great! thanks again
