### ISSUE TITLE
Put <img> tag into data

### ISSUE THREAD

**Issue by ahmadfzzz** [AndreSouzaAbreu/vue-data-table#4]
**Hi dude**

I want show image in table but i CANT!
I tried to put <img> into my Array to showing in Table, but after render that not show any image and just show text like this:
`<img src="example.com/img.png">`

`for (let index = 0; response.body.data.courses.length > index; index++) {`
     ` let need = {`
                            `id: index + 1,`
                            `name: response.body.data.courses[index].name,`
                            `slug: response.body.data.courses[index].slug,`
                            `cover: "<img src='"+response.body.data.courses[index].cover+"' width='40' height='40'/>",`
                            `category: response.body.data.courses[index].category.name,`
                            `teacher: response.body.data.courses[index].teacher.name,`
                            `price: addCommas(response.body.data.courses[index].price) + ' TR'`
                       ` };`
                       ` arr.unshift(need);`
`}`
how can i showing image in table ?

im so sry for my bad english

**Comment by AndreSouzaAbreu** [comment]
You are trying to display an image in a table cell, is that correct? It is display the text rather than html because in the source code of VueDataTable I used something like `<td>{{ content }}</td>` instead of  `<td v-html="content"></td>`. Since it requires a small change, I should be able to fix it soon. I will probably release a new version of VueDataTable (with no break changes) in two or three days.

**Comment by ahmadfzzz** [comment]
Thank you very much for your kindness
This data table saved my days dude, Im waiting for your update
Really Really Thank You <3

**Comment by AndreSouzaAbreu** [comment]
@ahmadfzzz  I have released a new minor version of Vue Data Table. To be able to display images in the table, or any other HTML, you have to add the prop unsafeHTML and set it to true (default is false due to security concerns with user input). In your case, I guess it would be something like

in template:
```html
<data-table v-bind="dataTableProps" />
```

in js:

```js
computed: {
  dataTableProps() {
    return {
      data: arr,
      columnKeys: ['id', 'name', 'slug', 'teacher', 'cover', 'price'],
      unsafeHTML: true, // this is the line you need to add
    }
  }
}
```

**Comment by AndreSouzaAbreu** [comment]
I will wait for your reply, and then close the issue.

Have nice coding :)

**Comment by ahmadfzzz** [comment]
> @ahmadfzzz I have released a new minor version of Vue Data Table. To be able to display images in the table, or any other HTML, you have to add the prop unsafeHTML and set it to true (default is false due to security concerns with user input). In your case, I guess it would be something like
> 
> in template:
> 
> ```
> <data-table v-bind="dataTableProps" />
> ```
> 
> in js:
> 
> ```js
> computed: {
>   dataTableProps() {
>     return {
>       data: arr,
>       columnKeys: ['id', 'name', 'slug', 'teacher', 'cover', 'price'],
>       unsafeHTML: true, // this is the line you need to add
>     }
>   }
> }
> ```

that was worked very good,
thank you for help me dude
have a great life ;)
