### ISSUE TITLE
Action Button cant modify the text column and its icons

### ISSUE THREAD

**Issue by paul-cylix** [AndreSouzaAbreu/vue-data-table#42]
I tried to follow the instructions and setup luckily it works but not fully, currently I am using Vue js version 2.6, I want to modify the design of the action button, but it doesn't work as expected, I think this is a bug in the package. please consider some modification in the action button like the font awesome icon and its action name, thank you, the best vue data-table that ive use so far

**Comment by AndreSouzaAbreu** [comment]
Action Buttons were available in previous version. In the current version there
aren't Action Buttons because they were replaced by custom components. You can use
a custom Vue Component to render a table cell of a specific column. This gives you
more flexibility and you can create your action buttons that way. Please, check out
the documentation; there is one example of Action Buttons using custom components.

**Comment by paul-cylix** [comment]
How can we set up the config? where do I need to paste the config code? i am having trouble following the tutorial?
I hope you add a demo app in code sandbox, it helps people like me

**Comment by paul-cylix** [comment]
is it possible to pass a data/object to the custom component / custom column and custom button ? if yes, how can i do it?

**Comment by paul-cylix** [comment]
is it possible to pass a dynamic data to a custom component? i want to pass a dynamic data from the parent component to custom component.

**Comment by resuldeger** [comment]
I changed some places and set up a structure like this. I don't know if it is correct in terms of usage. I wanted to navigate router without using store.
![image](https://user-images.githubusercontent.com/19941892/150667090-146bda02-d8e6-4b5a-9173-4e71e0eb3477.png)
![image](https://user-images.githubusercontent.com/19941892/150667144-123426a1-2c70-481e-b302-519e5841c353.png)
