### ISSUE TITLE
Documentation on the bootstrap dependency

### ISSUE THREAD

**Issue by GordonSo** [AndreSouzaAbreu/vue-data-table#43]
Following the setup, it suggested the requirement to:
`import "bootstrap/dist/css/bootstrap.min.css";`

It would be very useful to know which version of bootstrap is currently supported. 
I don't see such a dependency from the module's package.json neither.

**Comment by AndreSouzaAbreu** [comment]
I guess any version of Bootstrap 3 or 4 should work. There is not much
difference between these versions of Bootstrap; they keep compatibility
with most of the classes used by this Vue plugin (specifically, styles of
buttons, tables, pagination).

Thanks for the issue. I'll add the supported Bootstrap versions to the
documentation.

To be honest, I'm considering removing Bootstrap as a dependency, because
this plugin only uses a few classes of Bootstrap. Requiring users to
install Bootstrap may make their CSS bundle large. Copying the few CSS
classes from Boostrap into the stylesheet of this plugin seems to make
more sense to me. I'll think about it.

**Comment by GordonSo** [comment]
Thanks for the prompt reply, and the great work btw!

You are right, Bootstrap syntax should be largely the same. I was just concerned there will be some breaking or unexpected behaviour changes between releases, so it'd be nice to specify the tested version range; it'd also save the user from having to install it separately if they don't already use Bootstrap.

Boostrap breaking changes reference:
1. https://getbootstrap.com/docs/4.0/migration/
2. https://getbootstrap.com/docs/5.0/migration/

The idea of removing the dependency is the approach that other similar libraries, vuetify, ag-grid, have taken. As you said, they wrap into the package a css or scss export that the user will have to import at app.vue or component level. 

This'd probably mean it'd make sense to add custom classes than using the Bootstrap ones to provide some flexibility to override some styles without affecting other Bootstrap elements. But that's a subjective call. :) 

PS: I'm coming from a context migrating vue-2 to vue-3, and moving away from Bootstrap-Vue (Bootstrap-4) to native Boostrap 5, and also away from Vuetify (v-data-table) as their Vue 3 release is not out until Feb 2022 and it doesn't look like data-table is in their alpha documentation yet. So I think your great work will gain attract some attention in the coming months. 

Thanks for answering my question!

**Comment by AndreSouzaAbreu** [comment]
It is no longer necessary to install bootstrap to use this plugin.

I copied some of the bootstrap styles (actually, they are just a few) to
this plugin's internal stylesheets.

Thanks for the issue.
