### ISSUE TITLE
How can i add emit to data-table component?

### ISSUE THREAD

**Issue by paul-cylix** [AndreSouzaAbreu/vue-data-table#54]
i am trying to add emit from custom-component but the problem I don't know how can I add it to a data comes from database.

**this is the component. i don't know if this is the correct way to add emit**
`
<data-table v-bind="parametersTable1" @toggle-details="toggleDetailsStatus" />
`

**This is the data**
`  data() {
    return {
      requestArray: [{id: 1},{id: 2}],
    };
  },
`

**This is the method**
`
  methods: {
    toggleFavoriteStatus(){
      alert('uwu')
    },
  },
`

I hope you can help me. thanks and stay safe guys

**Comment by AndreSouzaAbreu** [comment]
Hello, thanks for the question!

There is no way you can emit from a custom component because VueDataTable
cannot know the name of the event will be emitted from the custom component. In
order for VueDataTable to listen to that event, I'd have to add a custom
directive, like

`<component @myevent='handleCustomEvent' :is=component v-bind="props"/>`

where "myevent" is the name of the event and "handleCustomEvent" would be a
method in VueDataTable that would be responsible for emitting the event from
the VueDataTable itself.

There several other ways to get around this. I can think of at least 3 of them:
use Vuex, use something like an Event Bus, or invoke some function direct on
the component by importing it. Probably, you are asking this question to add
the checkbox for mass-selection, right? I'll give you an example soon, and in
that example I'll show you how to use an Event Bus (this isn't complicated). I
like Event Bus because you can communicate between components without having to
use Vuex or emitting events, which may be overwhelming.

**Comment by AndreSouzaAbreu** [comment]
TO recap, there is no way to listen to events from custom components due to
the reasons explained earlier. However, you can achieve the same functionality
using Vuex, EventBus, or direct function calls. I add a demo example on
README on how to do that; see demo 4.

**Comment by paul-cylix** [comment]
Thank you. this helps me a lot. stay safe and god bless
