### ISSUE TITLE
"Insert" functionality

### ISSUE THREAD

**Issue by HowardWang0915** [AndreSouzaAbreu/vue-data-table#70]
First of all, thanks for the phenomenal work.
However, is there a way to add an insert functionality to this data table? For instance, the user may want to add a fruit manually to the fruit table when the user has no access to the source code.
Thanks!

**Comment by AndreSouzaAbreu** [comment]
Hello!

Yes, for sure there is!

For example, suppose you have a form in which the user inserts a fruit.

```vue
<template>
  <div id="app">
    <form>
      <label for="fruit">Fruit</label>
      <input type="text" id="fruit" name="fruit" v-model="fruitName">
      <label for="price">Fruit</label>
      <input type="number" id="price" name="price" v-model="fruitPrice">
      <button type="submit" @click="addFruit()">ADD</button>
    </form>
    <vue-data-table :data=fruits :columns=columns />
  </div>
</template>
<script>
export default {
  data() {
    return {
        fruitName: "",
        fruitPrice: 2,
        fruits: [ /* ... */],
        columns = ["name", "price"],
      }
  },
  methods() {
    addFruit() {
      this.fruits.push({ 'name' : this.fruitName, 'price': this.fruitPrice })
    }
  }
}
</script>
```

When the user submits the form, it triggers the method `addFruit()`. Since we
are using Vue, `this.fruitName` and `this.fruitPrice` will be synced with the
user input. By pushing it to the array of fruits, `this.fruits`, we will indeed
be adding a row to our table because Vue will take care of making sure that a
change in `this.fruit` (which is passed as the prop `data` to `VueDataTable`)
will be reflected in our UI.

**Comment by HowardWang0915** [comment]
Thanks for the example! This helped a lot.
